name: Tele2Rub Runner

on:
  workflow_dispatch:
    inputs:
      chat_id:
        description: 'Telegram Chat ID'
        required: true
      message_id:
        description: 'Telegram Message ID'
        required: true
      status_message_id:
        description: 'Message ID to edit'
        required: false
      should_zip:
        description: 'Zip the file before uploading'
        required: false

# این بخش سیستم صف (Queue) را ایجاد می‌کند
concurrency:
  group: tele2rub-queue
  cancel-in-progress: false # بسیار مهم: کارهای قبلی نباید لغو شوند، باید در صف منتظر بمانند

jobs:
  transfer-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pyrogram tgcrypto rubpy pyzipper

      - name: Run Tele2Rub Core
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          RUBIKA_SESSION_BASE64: ${{ secrets.RUBIKA_SESSION_BASE64 }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
          MESSAGE_ID: ${{ github.event.inputs.message_id }}
          STATUS_MESSAGE_ID: ${{ github.event.inputs.status_message_id }}
          SHOULD_ZIP: ${{ github.event.inputs.should_zip }}
        run: python runner.py
