- name: Recreate Rubika Session
        run: |
          echo "${{ secrets.RUBIKA_SESSION_BASE64 }}" | base64 -d > rubsession.sqlite

      - name: Run Transfer Engine
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ github.event.inputs.chat_id }}
          MESSAGE_ID: ${{ github.event.inputs.message_id }}
        run: |
          python main.py
